portfolio/urls.py
from django.urls import path
import portfolio.views
from django.conf.urls import include, url
from .views import MyView, AboutView, ServicesView, PortfolioView, PriceView, BlogHomeView, PagesView, \
    ContactView,BlogSingleView
    # MyDetailView, BlogSingleView
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', MyView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('services/', ServicesView.as_view(), name='services'),
    path('portfolio/', PortfolioView.as_view(), name='portfolio'),
    path('price/', PriceView.as_view(), name='price'),
    path('bloghome/', BlogHomeView.as_view(), name='bloghome'),
    path('blogsingle/', BlogSingleView.as_view(), name='blogsingle'),
    # path('bloghome/<int:pk>/', MyDetailView.as_view(), name='detail'),
    path('pages/', PagesView.as_view(), name='pages'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('sendmail/', portfolio.views.sendmail, name='sendmail'),
    path('contactmessage/', portfolio.views.contactmessage, name='contactmessage'),
]

untitled1/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/forms.py
from django import forms
from .models import NewsSubscription, ContactForm


class SendMailForm(forms.ModelForm):
    class Meta:
        model = NewsSubscription
        fields = ["news_email"]


class SendMessageForm(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields = ["name", "email", "subject", "message"]

portfolio/views.py
from django.views.generic import TemplateView, DetailView
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.http import HttpResponse
from django.conf import settings
from django.core.mail import send_mail
from .models import LatestProjectFeatures, MyOfferedServices, Blog, ClientFeedbackAboutMe, Personal, About, \
    ServicesComplete, \
    ChosePlan, ImageLabel, ToolExpertness, Qualification, Designation, QuestionAnswer, BlogHomeBanner, \
    BlogHomeCategoryWidget, \
    BlogHomeContent, BlogHomeSearchPost, BlogHomePopularPost, BlogHomeCategory, BlogHomeNewsLetter, BlogSinglePost, \
    BlogSingleComment, BlogSingleLeaveComment, BlogSingleTagsCloud, NewsSubscription, ContentFormAddressInfo, ContactForm
from django.views.generic import ListView


def sendmail(request):
    if request.method == 'POST':
        email = request.POST["email"]
        try:
            email = NewsSubscription.objects.get(news_email=request.POST['email'])
            return HttpResponse({'You are already Subscribed'})
        except:
            send_mal = NewsSubscription(news_email=email)
            send_mal.save()
            if request.method == 'POST':
                email = request.POST['email']
                from_email = settings.EMAIL_HOST_USER
                send_mail(subject='MedArt', message='Thank You for subscribing MedArt.', from_email=from_email,
                          recipient_list=[email], fail_silently=False)
            return HttpResponse({'You are Subscribed successfully'})
    # return HttpResponse('method not allowes', status=405)


class MyView(ListView):
    context_object_name = 'name'
    template_name = 'portfolio/index.html'
    queryset = LatestProjectFeatures.objects.all()

    def get_context_data(self, **kwargs):
        context = super(MyView, self).get_context_data(**kwargs)
        context['service'] = MyOfferedServices.objects.all()
        context['blog'] = Blog.objects.all()
        context['feature'] = LatestProjectFeatures.objects.all()
        context['feedback'] = ClientFeedbackAboutMe.objects.all()
        context['personal'] = Personal.objects.all()
        context['about'] = About.objects.all()
        context['complete_service'] = ServicesComplete.objects.all()
        context['chose_plan'] = ChosePlan.objects.all()
        context['label'] = ImageLabel.objects.all()
        return context


class AboutView(ListView):
    context_object_name = 'name'
    template_name = 'portfolio/about.html'
    queryset = About.objects.all()

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context['about'] = About.objects.all()
        context['tool_expert'] = ToolExpertness.objects.all()
        context['qualification'] = Qualification.objects.all()
        context['designation'] = Designation.objects.all()
        context['feedback'] = ClientFeedbackAboutMe.objects.all()
        context['label'] = ImageLabel.objects.all()

        return context


class ServicesView(TemplateView):
    context_object_name = 'name'
    template_name = 'portfolio/services.html'
    queryset = MyOfferedServices.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ServicesView, self).get_context_data(**kwargs)
        context['service'] = self.queryset
        context['complete_service'] = ServicesComplete.objects.all()
        context['chose_plan'] = ChosePlan.objects.all()
        context['feedback'] = ClientFeedbackAboutMe.objects.all()

        return context


class PortfolioView(ListView):
    context_object_name = 'name'
    template_name = 'portfolio/portfolio.html'
    queryset = LatestProjectFeatures.objects.all()

    def get_context_data(self, **kwargs):
        context = super(PortfolioView, self).get_context_data(**kwargs)
        context['feature'] = self.queryset

        return context


class PriceView(TemplateView):
    context_object_name = 'name'
    template_name = 'portfolio/price.html'
    queryset = ChosePlan.objects.all()

    def get_context_data(self, **kwargs):
        context = super(PriceView, self).get_context_data(**kwargs)
        context['chose_plan'] = self.queryset
        context['question_answer'] = QuestionAnswer.objects.all()
        return context


class BlogHomeView(TemplateView):
    context_object_name = 'name'
    template_name = 'portfolio/blog-home.html'
    queryset = BlogHomeBanner.objects.all()

    def get_context_data(self, **kwargs):
        context = super(BlogHomeView, self).get_context_data(**kwargs)
        context['blog_banner'] = self.queryset
        context['blog_category_widget'] = BlogHomeCategoryWidget.objects.all()
        context['blog_content'] = BlogHomeContent.objects.all()
        context['blog_search_post'] = BlogHomeSearchPost.objects.all()
        context['blog_popular_post'] = BlogHomePopularPost.objects.all()
        context['blog_home_category'] = BlogHomeCategory.objects.all()
        context['blog_home_newsletter'] = BlogHomeNewsLetter.objects.all()

        return context


class BlogSingleView(TemplateView):
    context_object_name = 'name'
    template_name = 'portfolio/blog-singl.html'


# class MyDetailView(DetailView):
#     model = BlogHomeContent
#     context_object_name = 'blog'
#     template_name = 'portfolio/blog-single.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(MyDetailView, self).get_context_data(**kwargs)
#         context['blog_content'] = BlogHomeContent.objects.all()
#         context['blog_single_post'] = BlogSinglePost.objects.all()
#         context['blog_search_post'] = BlogHomeSearchPost.objects.all()
#         context['blog_popular_post'] = BlogHomePopularPost.objects.all()
#         context['blog_home_category'] = BlogHomeCategory.objects.all()
#         context['blog_home_newsletter'] = BlogHomeNewsLetter.objects.all()
#         context['blog_single_comment'] = BlogSingleComment.objects.all()
#         context['blog_single_leave_comment'] = BlogSingleLeaveComment.objects.all()
#         context['blog_single_tag_cloud'] = BlogSingleTagsCloud.objects.all()
#
#         return context
#
#     def get_object(self):
#         queryset = BlogHomeContent.objects.get(pk=self.kwargs['pk'])
#         return queryset


class PagesView(TemplateView):
    template_name = "portfolio/elements.html"


class ContactView(TemplateView):
    template_name = "portfolio/contact.html"
    model = ContentFormAddressInfo
    context_object_name = 'blog'

    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        context['content_form_address'] = ContentFormAddressInfo.objects.all()

        return context


def contactmessage(request):
    name = request.POST["name"]
    email = request.POST["email"]
    subject = request.POST["subject"]
    message = request.POST["message"]
    send_mal = ContactForm(email=email, name=name, subject=subject, message=message)
    send_mal.save()

    if request.method == 'POST':
        name = request.POST["name"]
        email = request.POST["email"]
        subject = request.POST["subject"]
        message = request.POST["message"]
        from_email = settings.EMAIL_HOST_USER
        send_mail(subject=subject, message=message, from_email=from_email,
                  recipient_list=[email], fail_silently=False)
    return HttpResponse({'Your Message is sent Successfully. We will contact you soon. Thank you'})

portfolio/templates/base.html
{% load static %}
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Personal</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="{% static "css/linearicons.css" %}">
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery-ui.css" %}">
    <link rel="stylesheet" href="{% static "css/nice-select.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
</head>
<body>
<header id="header">
    <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a href="{% url 'portfolio:home' %}"><img src="{% static 'img/logo.png' %}" alt="" title=""/></a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li><a href="{% url 'portfolio:home' %}">Home</a></li>
                    <li><a href="{% url 'portfolio:about' %}">About</a></li>
                    <li><a href="{% url 'portfolio:services' %}">Services</a></li>
                    <li><a href="{% url 'portfolio:portfolio' %}">Portfolio</a></li>
                    <li><a href="{% url 'portfolio:price' %}">Pricing</a></li>
                    <li class="menu-has-children"><a href="">Blog</a>
                        <ul>
                            <li><a href="{% url 'portfolio:bloghome' %}">Blog Home</a></li>
                            <li><a href="{% url 'portfolio:blogsingle' %}">Blog Single</a></li>
                        </ul>
                    </li>
                    <li class="menu-has-children"><a href="">Pages</a>
                        <ul>
                            <li><a href="{% url 'portfolio:pages' %}">Elements</a></li>
                            <li class="menu-has-children"><a href="">Level 2 </a>
                                <ul>
                                    <li><a href="#">Item One</a></li>
                                    <li><a href="#">Item Two</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="{% url 'portfolio:contact' %}">Contact</a></li>
                </ul>
            </nav><!-- #nav-menu-container -->
        </div>
    </div>
</header><!-- #header -->

{% block content %}


{% endblock %}

<!-- start footer Area -->
<footer class="footer-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h4>About Me</h4>
                    <p>
                        We have tested a number of registry fix and clean utilities and present our top 3 list on our
                        site for your convenience.
                    </p>
                    <p class="footer-text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                        All rights reserved | This template is made with <i class="fa fa-heart-o"
                                                                            aria-hidden="true"></i> by <a
                            href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h4>Newsletter</h4>
                    <p>Stay updated with our latest trends</p>
                    <div class="" id="mc_embed_signup">
                        <form target="_blank"
                              id="user_subscription">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" id="email" class="form-control" name="EMAIL" placeholder="Enter Email Address"
                                       onfocus="this.placeholder = ''"
                                       onblur="this.placeholder = 'Enter Email Address '" required="" type="email">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <span class="lnr lnr-arrow-right"></span>
                                    </button><br/><br/>

                                </div>
                                <div class="info"></div>
                            </div>
                            <span id="successful-message"></span>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
                <div class="single-footer-widget">
                    <h4>Follow Me</h4>
                    <p>Let us be social</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
{#<!-- End footer Area -->#}
{#<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"#}
{#        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"#}
{#        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"#}
{#        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"#}
{#        crossorigin="anonymous"></script>#}

<script src="{% static "js/vendor/jquery-2.2.4.min.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "js/vendor/bootstrap.min.js" %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{% static "js/easing.min.js" %}"></script>
<script src="{% static "js/hoverIntent.js" %}"></script>
<script src="{% static "js/superfish.min.js" %}"></script>
<script src="{% static "js/jquery.ajaxchimp.min.js" %}"></script>
<script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/jquery.tabs.min.js" %}"></script>
<script src="{% static "js/jquery.nice-select.min.js" %}"></script>
<script src="{% static "js/isotope.pkgd.min.js" %}"></script>
<script src="{% static "js/waypoints.min.js" %}"></script>
<script src="{% static "js/jquery.counterup.min.js" %}"></script>
<script src="{% static "js/simple-skillbar.js" %}"></script>
<script src="{% static "js/owl.carousel.min.js" %}"></script>
<script src="{% static "js/mail-script.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>
<script type="text/javascript">
    $(document).on('submit', '#user_subscription', function (e) {

        e.preventDefault();
        {#$(".msk").addClass('fa fa-spinner fa-spin')#}
        $.ajax({
            type: "POST",
            url: "/sendmail/",
            data: {
                email: $('#email').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function (data) {
                $('#successful-message').text(data)
                {#$(".msk").removeClass('fa fa-spinner fa-spin')#}

            },
            error: function (err) {

            }
        });

    });</script>
</body>
</html>